### ISSUE TITLE
[BUG] segfault when using a specific theme

### ISSUE THREAD

**Issue by LamprosPitsillos** [davatorium/rofi#1703]
### Rofi version (rofi -v)

Version: 1.7.5

### Configuration

https://gist.github.com/LamprosPitsillos/0bf001b4ac6b833fe282bce2099a5128

### Theme

https://gist.github.com/LamprosPitsillos/a6db77ee372c299a6774d6455116b01a

### Timing report

https://gist.github.com/LamprosPitsillos/e1966a7f70cc30706c0c17ca699ebfb4

### Launch command

rofi -no-config -dmenu -p "Scrot Name: " -theme Input  

### Step to reproduce

+ Get this theme on your system https://gist.github.com/LamprosPitsillos/53efafe5afaea9f81bc912525c3cb79b
+ Also use the above launch command 
+ You should get a SEGFAULT

### Expected behavior

Load the theme and start the picker

### Actual behavior

SEGFAULTs immediately  

### Additional information

OS: Artix Linux x86_64 
Kernel: 5.19.6-artix1-1

**Comment by DaveDavenport** [comment]
Cannot reproduce here with git nor 1.7.5.  Can you get a backtrace?

Also provide distro name & version

**Comment by LamprosPitsillos** [comment]
` gdb --args rofi -dmenu -p "Scrot Name: " -theme Input `

I tried using the above method but my computer freezes for some reason as soon as the segfault occurs...

**Comment by DaveDavenport** [comment]
yeah, that is not going to work. You need to get a coredump, then run gdb on that. 
See `man rofi-debugging`  the exact way to get coredump sometimes differs per distro.

**Comment by LamprosPitsillos** [comment]
I am finding it a bit difficult to get a core dump without `systemd` on my system.
Here is a log for now : 
```
[Timings]: 0.000001 (0.000000): Started
[Timings]: 0.000483 (0.000483): source/rofi.c:main:884 
[default]: Parsing string: 'configuration {

    // Timeout from user input.
    timeout {
        // The delay after inactivity to execute action.
        delay: 0;
        // The action to execute once the delay expires.
        action: "kb-cancel";
    }

    // File browser mode.
    filebrowser {
        sorting-method:    "name";
        directories-first: true;
    }
}

@theme "default"
'
[Timings]: 0.003276 (0.002793): source/rofi.c:main:935 
[Timings]: 0.003543 (0.000267): source/rofi.c:main:942 Setup Locale
[Rofi]: Parse plugin path: /usr/lib/rofi
[Rofi]: Looking into: /usr/lib/rofi for plugins
[Timings]: 0.004244 (0.000701): source/rofi.c:main:944 Collect MODES
[Timings]: 0.004309 (0.000065): source/rofi.c:main:946 Setup MODES
[Timings]: 0.004370 (0.000061): source/rofi.c:main:950 Setup mainloop
[Timings]: 0.004679 (0.000309): source/rofi.c:main:953 NK Bindings
[Timings]: 0.007351 (0.002672): source/xcb.c:display_setup:1507 Open Display
[X11Helper]: Query RANDR for monitor layout.
[X11Helper]: Randr XCB api version: 1.6.
[X11Helper]: Found randr version: 1.5
[X11Helper]: Found window manager: |LG3DY|
[Timings]: 0.009606 (0.002255): source/xcb.c:display_setup:1523 Setup XCB
[Timings]: 0.023771 (0.014165): source/rofi.c:main:960 Setup Display
[Timings]: 0.023853 (0.000082): source/rofi.c:main:964 Setup abe
[Timings]: 0.023875 (0.000022): source/rofi.c:main:1003 Parse theme
[Helper]: Opening theme, testing: Input

[Helper]: Opening theme, testing: /home/inferno/.config/rofi/themes/Input.rasi
[Helper]: Opening theme, testing: /home/inferno/.config/rofi/Input.rasi
[Helper]: Opening theme, testing: /home/inferno/.local/share/rofi/themes/Input.rasi
[GLib-GIO]: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
[default]: Parsing top file: '/home/inferno/.local/share/rofi/themes/Input.rasi'
[Timings]: 0.030922 (0.007047): source/rofi.c:main:1011 Parsed theme
[XrmOptions]: str: "configuration { p: Scrot Name: ;}"

[default]: Parsing string: 'configuration { p: Scrot Name: ;}'
[Parser]: Failed to parse theme:
<big><b>Error while parsing theme:</b></big> <i>configuration { p: Scrot Name: ;}</i>
	Parser error: <span size="smaller" style="italic">syntax error, unexpected invalid property value</span>
	Location:     line 1 column 19 to line 1 column 36

[XrmOptions]: str: "configuration { p: "Scrot Name: ";}"

[default]: Parsing string: 'configuration { p: "Scrot Name: ";}'
[XrmOptions]: Option: p is not found.
[XrmOptions]: Adding option: p to backup list.
[XrmOptions]: str: "configuration { log: l;}"

[default]: Parsing string: 'configuration { log: l;}'
[Parser]: Failed to parse theme:
<big><b>Error while parsing theme:</b></big> <i>configuration { log: l;}</i>
	Parser error: <span size="smaller" style="italic">syntax error, unexpected invalid property value</span>
	Location:     line 1 column 21 to line 1 column 24

[XrmOptions]: str: "configuration { log: "l";}"

[default]: Parsing string: 'configuration { log: "l";}'
[XrmOptions]: Option: log is not found.
[XrmOptions]: Adding option: log to backup list.
[Timings]: 0.031194 (0.000272): source/rofi.c:main:1019 Load cmd config 
[Timings]: 0.031517 (0.000323): source/view.c:rofi_view_workers_initialize:2288 Setup Threadpool, start
[Timings]: 0.031575 (0.000058): source/view.c:rofi_view_workers_initialize:2312 Setup Threadpool, done
[Timings]: 0.031590 (0.000015): source/rofi.c:main:1101 Workers initialize
[Helpers.IconFetcher]: Add image extension: ani
[Helpers.IconFetcher]: Add image extension: png
[Helpers.IconFetcher]: Add image extension: bmp
[Helpers.IconFetcher]: Add image extension: gif
[Helpers.IconFetcher]: Add image extension: ico
[Helpers.IconFetcher]: Add image extension: cur
[Helpers.IconFetcher]: Add image extension: jpeg
[Helpers.IconFetcher]: Add image extension: jpe
[Helpers.IconFetcher]: Add image extension: jpg
[Helpers.IconFetcher]: Add image extension: pnm
[Helpers.IconFetcher]: Add image extension: pbm
[Helpers.IconFetcher]: Add image extension: pgm
[Helpers.IconFetcher]: Add image extension: ppm
[Helpers.IconFetcher]: Add image extension: tiff
[Helpers.IconFetcher]: Add image extension: tif
[Helpers.IconFetcher]: Add image extension: xpm
[Helpers.IconFetcher]: Add image extension: xbm
[Helpers.IconFetcher]: Add image extension: tga
[Helpers.IconFetcher]: Add image extension: targa
[Helpers.IconFetcher]: Add image extension: icns
[Helpers.IconFetcher]: Add image extension: qtif
[Helpers.IconFetcher]: Add image extension: qif
[Helpers.IconFetcher]: Add image extension: wmf
[Helpers.IconFetcher]: Add image extension: apm
[Helpers.IconFetcher]: Add image extension: avif
[Helpers.IconFetcher]: Add image extension: heif
[Helpers.IconFetcher]: Add image extension: heic
[Helpers.IconFetcher]: Add image extension: avif
[Helpers.IconFetcher]: Add image extension: jxl
[Helpers.IconFetcher]: Add image extension: svg
[Helpers.IconFetcher]: Add image extension: svgz
[Helpers.IconFetcher]: Add image extension: svg.gz
[Timings]: 0.054937 (0.023347): source/rofi.c:main:1103 Icon fetcher initialize
[Timings]: 0.054988 (0.000051): source/rofi.c:main:1111 Pid file created
[Timings]: 0.055002 (0.000014): source/rofi.c:main:1117 Text box setup
[Timings]: 0.055981 (0.000979): source/rofi.c:main:1124 Setup late Display
[X11Helper]: Monitor active
[X11Helper]: Monitor lookup  by name : -5
[X11Helper]: Monitor lookup  by name failed: -5
[X11Helper]: Monitor id: -5
[Theme]: Resolving link to fg
[Theme]: Resolving link fg found: fg
[Theme]: Resolving link to bg-alt
[Theme]: Resolving link bg-alt found: bg-alt
[Theme]: Resolving link to fg
[Theme]: Resolving link fg found: fg
[Theme]: Resolving link to bg-alt
[Theme]: Resolving link bg-alt found: bg-alt
[Timings]: 0.056415 (0.000434): source/rofi.c:main:1128 Theme setup
[Timings]: 0.056503 (0.000088): source/rofi.c:startup:719 Startup
[Timings]: 0.056525 (0.000022): source/rofi.c:startup:728 Grab keyboard
[Timings]: 0.056622 (0.000097): source/view.c:__create_window:808 xcb create window
[Timings]: 0.056650 (0.000028): source/view.c:__create_window:812 xcb create gc
[Timings]: 0.059116 (0.002466): source/view.c:__create_window:822 create cairo surface
[Timings]: 0.059768 (0.000652): source/view.c:__create_window:831 pango cairo font setup
[X11Helper]: Monitor active
[Theme]: Theme entry: #window  property border-radius unset.
[Theme]: Theme entry: #window  property cursor unset.
[Theme]: Theme entry: #window  property enabled unset.
[Theme]: Theme entry: #window  property orientation unset.
[Theme]: Theme entry: #window  property font unset.
[Timings]: 0.059998 (0.000230): source/view.c:__create_window:875 configure font
[Timings]: 0.082136 (0.022138): source/view.c:__create_window:883 textbox setup
[Timings]: 0.082177 (0.000041): source/view.c:__create_window:897 setup window attributes
[Theme]: Theme entry: #window  property fullscreen unset.
[Timings]: 0.082202 (0.000025): source/view.c:__create_window:912 setup window fullscreen
[Timings]: 0.082213 (0.000011): source/view.c:__create_window:919 setup window name and class
[Timings]: 0.082224 (0.000011): source/view.c:rofi_view_setup_fake_transparency:737 Fake start
[Timings]: 0.082234 (0.000010): source/view.c:__create_window:928 setup startup notification
[Timings]: 0.082244 (0.000010): source/view.c:__create_window:930 done
[Timings]: 0.082265 (0.000021): source/rofi.c:startup:730 Create Window
[Timings]: 0.082276 (0.000011): source/rofi.c:startup:732 Parse ABE
[X11Helper]: Monitor active
[Timings]: 0.082297 (0.000021): source/rofi.c:startup:735 Config sanity check
[Timings]: 0.082368 (0.000071): source/view.c:rofi_view_create:2106 
[Timings]: 0.082388 (0.000020): source/view.c:rofi_view_create:2131 Startup notification
[Timings]: 0.082398 (0.000010): source/view.c:rofi_view_create:2134 Get active monitor
[Theme]: Theme entry: #window  property border-radius unset.
[Theme]: Theme entry: #window  property cursor unset.
[Theme]: Theme entry: #window  property enabled unset.
[Theme]: Theme entry: #window  property orientation unset.
[Theme]: Theme entry: #mainbox  property border-radius unset.
[Theme]: Theme entry: #mainbox  property cursor unset.
[Theme]: Theme entry: #mainbox  property enabled unset.
[Theme]: Theme entry: #mainbox  property orientation unset.
[Theme]: Theme entry: #mainbox  property expand unset.
[Widgets.Box]: Widgets to large (height) for box: -4 0
[Theme]: Theme entry: #inputbar  property border-radius unset.
[Theme]: Theme entry: #inputbar  property cursor unset.
[Theme]: Theme entry: #inputbar  property enabled unset.
[Theme]: Theme entry: #inputbar  property orientation unset.
[Theme]: Theme entry: #inputbar  property expand unset.
[Widgets.Box]: Widgets to large (width) for box: -2 0
[Widgets.Box]: Widgets to large (height) for box: -2 0
[Widgets.Box]: Widgets to large (height) for box: -4 0
[Widgets.Box]: Widgets to large (height) for box: -2 0
[Widgets.Box]: Widgets to large (height) for box: -4 0
[Theme]: Theme entry: #prompt  property padding unset.
[Theme]: Theme entry: #prompt  property border-radius unset.
[Theme]: Theme entry: #prompt  property cursor unset.
[Theme]: Theme entry: #prompt  property enabled unset.
[Theme]: Theme entry: #prompt normal.normal property border-radius unset.
[Theme]: Theme entry: #prompt normal.normal property markup unset.
[Theme]: Theme entry: #prompt normal.normal property str unset.
[Theme]: Theme entry: #prompt normal.normal property content unset.
[Theme]: Theme entry: #prompt normal.normal property placeholder unset.
[Widgets.Box]: Widgets to large (width) for box: -2 0
[Widgets.Box]: Widgets to large (height) for box: -2 0
[Widgets.Box]: Widgets to large (height) for box: -4 0
[Theme]: Theme entry: #prompt normal.normal property vertical-align unset.
[Theme]: Theme entry: #prompt normal.normal property horizontal-align unset.
[Widgets.Box]: Widgets to large (width) for box: -2 0
[Widgets.Box]: Widgets to large (height) for box: -2 0
[Widgets.Box]: Widgets to large (height) for box: -4 0
[Theme]: Theme entry: #prompt normal.normal property expand unset.
[Theme]: Theme entry: #prompt normal.normal property width unset.
[Widgets.Box]: Widgets to large (width) for box: -2 0
[Widgets.Box]: Widgets to large (height) for box: -2 0
[Widgets.Box]: Widgets to large (height) for box: -4 0
[Theme]: Theme entry: #entry  property padding unset.
[Theme]: Theme entry: #entry  property border-radius unset.
[Theme]: Theme entry: #entry  property cursor unset.
[Theme]: Theme entry: #entry  property enabled unset.
[Theme]: Theme entry: #entry normal.normal property border-radius unset.
[Theme]: Theme entry: #entry normal.normal property markup unset.
[Theme]: Theme entry: #entry normal.normal property str unset.
[Theme]: Theme entry: #entry normal.normal property content unset.
[Theme]: Theme entry: #entry normal.normal property placeholder unset.
[Theme]: Theme entry: #entry normal.normal property blink unset.
[Theme]: Theme entry: #entry normal.normal property vertical-align unset.
[Theme]: Theme entry: #entry normal.normal property horizontal-align unset.
[Theme]: Theme entry: #entry normal.normal property expand unset.
[Theme]: Theme entry: #prompt normal.normal property width unset.
[Widgets.Box]: Widgets to large (width) for box: -2 0
[Theme]: Theme entry: #prompt normal.normal property width unset.
[Widgets.Box]: Widgets to large (width) for box: -2 0
[Widgets.Box]: Widgets to large (height) for box: -2 0
[Widgets.Box]: Widgets to large (height) for box: -4 0
[Widgets.Box]: Widgets to large (height) for box: -2 0
[Widgets.Box]: Widgets to large (height) for box: -4 0
[Theme]: Theme entry: #window  property height unset.
[Theme]: Theme entry: #window  property location unset.
[Theme]: Theme entry: #window  property anchor unset.
[Theme]: Theme entry: #window  property x-offset unset.
[Theme]: Theme entry: #window  property y-offset unset.
[View]: Re-size window based internal request: 576x56.
[Theme]: Theme entry: #prompt normal.normal property width unset.
[Timings]: 0.088671 (0.006273): source/view.c:rofi_view_refilter_real:1170 Filter start
[Timings]: 0.088689 (0.000018): source/view.c:rofi_view_refilter_real:1175 Filter reload rows
[Timings]: 0.088709 (0.000020): source/view.c:rofi_view_refilter_real:1180 Filter tokenize
[Timings]: 0.088720 (0.000011): source/view.c:rofi_view_refilter_real:1255 Filter matching done
[Timings]: 0.088731 (0.000011): source/view.c:rofi_view_refilter_real:1268 Update filter lines
[Theme]: Theme entry: #window  property height unset.
[Timings]: 0.088871 (0.000140): source/view.c:rofi_view_refilter_real:1286 Filter resize window based on window 
[Timings]: 0.088886 (0.000015): source/view.c:rofi_view_refilter_real:1288 Filter done
[View]: Redraw view
[Timings]: 0.088905 (0.000019): source/view.c:rofi_view_update:1123 
[Timings]: 0.088936 (0.000031): source/view.c:rofi_view_update:1141 Background
[Theme]: Resolving link to bg
[Theme]: Resolving link bg found: bg
[Theme]: Theme entry: #window  property background-image unset.
[Theme]: Theme entry: #mainbox  property background-image unset.
[Theme]: Theme entry: #inputbar  property background-image unset.
[Theme]: Theme entry: #prompt normal.normal property background-image unset.
[Theme]: Theme entry: #entry normal.normal property background-image unset.
[Timings]: 0.089433 (0.000497): source/view.c:rofi_view_update:1147 widgets

```

**Comment by DaveDavenport** [comment]
I really need a backtrace. Did you check the manpage? the first hint it gives (ulimit -c unlimited) should work ..

**Comment by LamprosPitsillos** [comment]
Yes i did ,but i thought i had to make it crash inside of gdb,sorry... Either way here is the backtrace .
```
Core was generated by `rofi -no-config -dmenu -p Scrot Name:  -theme Input -log l'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000559189951664 in listview_set_selected ()
[Current thread is 1 (Thread 0x7fab1d3c88c0 (LWP 15096))]
(gdb) bt
#0  0x0000559189951664 in listview_set_selected ()
#1  0x000055918993b119 in rofi_view_set_selected_line ()
#2  0x0000559189962651 in dmenu_mode_dialog ()
#3  0x000055918993f08f in  ()
#4  0x00007fab1e24db2b in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#5  0x00007fab1e2a3e79 in  () at /usr/lib/libglib-2.0.so.0
#6  0x00007fab1e24d08f in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#7  0x00005591899333af in main ()
```

**Comment by DaveDavenport** [comment]
thx.

**Comment by DaveDavenport** [comment]
I think the above commit should have fixed it.
Please re-open if not .
